
services:
  front-despacho:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-despacho
    environment:
      
      BACK_VENTAS_HOST: ${BACK_VENTAS_HOST:-host.docker.internal}
      BACK_VENTAS_PORT: ${BACK_VENTAS_PORT:-8080}
      BACK_DESPACHOS_HOST: ${BACK_DESPACHOS_HOST:-host.docker.internal}
      BACK_DESPACHOS_PORT: ${BACK_DESPACHOS_PORT:-8081}
    ports:
      - "80:80"
    restart: unless-stopped
